# .streamlit/secrets.toml
VGG16_URL = "https://drive.google.com/uc?id=1rp0oq4LF2ty4aNyKwWVxwZOP9BGqI2Zk"
RESNET50_URL = "https://drive.google.com/uc?id=1TXCM6vpxaSofye0bfTYsfDMfpma02oDd"
DENSENET121_URL = "https://drive.google.com/uc?id=1DBhSDAOSa3w_t8tB4sFVm43M8Fr7fxsC"
EFFICIENTNETV2S_URL = "https://drive.google.com/uc?id=1ljFFlwsbp7vQ5qWBICV4hCVZ51AyvDCY"
